Desktop feature
amanuelbelete95/Portfolio pull request #4
Opened 2023-01-19 19:21 UTC by amanuelbelete95

**List of activities**

-  Used media queries in my CSS (Desktop: 768px or wider)
-  Used Grid and Flexbox to lay out items.
-  The desktop version of the portfolio is similar to the Figma template provided
-  Checked linter errors for CSS and HTML file
-  Used correct GitHub flow

2023-01-19 20:03 UTC, levy002 requested changes
## Hello @amanuelbelete95   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 20:03 UTC, levy002 commented on style.css
>    }
- [ ] Kindly make sure the background image is visible on the `About Myself` section on the desktop version. :wink: 

   - ### YOUR DESIGN
   
      ![image](https://user-images.githubusercontent.com/87197412/213544692-57f52bc5-28c5-4d51-8237-a3636a0da61f.png)

   - ### FIGMA DESIGN
   
      ![image](https://user-images.githubusercontent.com/87197412/213544839-0b1c1393-ff72-474f-916c-3219e0388f64.png)

2023-01-19 20:03 UTC, levy002 commented on style.css
>    }
- [ ] Kindly make sure your project cards are visible on the desktop version.

   - ### YOUR DESIGN
   
     ![image](https://user-images.githubusercontent.com/87197412/213545448-04829ea6-6986-42ca-a73f-bf995ce64f54.png)

   - ### FIGMA DESIGN
   
     ![image](https://user-images.githubusercontent.com/87197412/213545567-123f4221-dd49-4a69-92fc-3267cfe1d1e4.png)

2023-01-19 20:03 UTC, levy002 commented on style.css
>    }
- [ ] Kindly make sure to align the headline content correctly and make sure the background image is visible on the mobile version.

   - ### YOUR DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/213546289-6b5faaac-5d58-4c66-acf5-4bdd9acce677.png)

   - ### FIGMA DESIGN
   
     ![image](https://user-images.githubusercontent.com/87197412/213546833-4d8044ec-3470-43de-bc8c-5441cfed9493.png)

2023-01-20 07:00 UTC, emmiiorji requested changes
Hi @amanuelbelete95, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔️

- Linter checks are passing
- Proper use of GitHub flow
- Good commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 07:00 UTC, emmiiorji commented on style.css
>    }
You have done great by making the project cards show up on the desktop version as requested by the previous reviewer. Kindly ensure that the design of the cards follow the figma design.

The card design with a cursor over it and the "see project" button shows how each of the cards should appear when they're hovered over. The remaining cards show how the cards should normally look.

Card when hovered:
![image](https://user-images.githubusercontent.com/20554583/213634559-fd9596b6-5604-40a5-98c6-eae6e8d3601d.png)

Normal display of card:
![image](https://user-images.githubusercontent.com/20554583/213634678-60b36323-5870-4d0e-b7de-cde39d086fdb.png)

2023-01-20 07:00 UTC, emmiiorji commented on index.html
>          <h3 class="story-title">Multi-Post Stories</h3>
[Optional] I recommend that you design the leading project as close to the design as possible. The image as shown below occupies a larger with than the description.

Your design:
![image](https://user-images.githubusercontent.com/20554583/213635926-7388ea7a-7a78-417e-b217-bba2f2539cfc.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/213635947-2608e4ea-64e9-4755-98bd-d94bc5d7fba2.png)

2023-01-20 07:00 UTC, emmiiorji commented on index.html
> +            I can help you build a product , feature or website Look through
[Optional] I suggest that you remove the horizontal overflow on the page in order to give a better user experience on the website.

Your design:
![image](https://user-images.githubusercontent.com/20554583/213636498-9484d2db-1bbc-4d51-8754-b4d3d398adfa.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/213636308-a9be71d0-75ee-4c0d-8a1d-ee3237bb63a6.png)

2023-01-20 11:37 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @amanuelbelete95 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- ❗ I have noticed that you have not applied the optional changes requested by the previous reviewer about the horizontal scroll effect. Kindly ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-01-20 12:55 UTC, merged